export const UPDATE_CELL = 'UPDATE_CELL';
export const UPDATE_SELECTION = 'UPDATE_SELECTION';
export const UPDATE_FILTER = "UPDATE_FILTER";
export const UPDATE_SAVING_PROGRESS = "UPDATE_SAVING_PROGRESS";